"""SRD ingestion: pinned raw dataset -> typed models (P0.2).

The raw data under `data/srd/raw/` is vendored and version-pinned (OD-7); the
normalized output is regenerated by `dndc srd ingest` and never committed, so a
normalization bug cannot be frozen into the repo.

Nothing here touches a model or the network. Ingestion is a pure transform over files.
"""

from dndc.srd.ingest import (
    DEFAULT_NORMALIZED_ROOT,
    DEFAULT_RAW_ROOT,
    IngestReport,
    SRDIngestError,
    ingest,
    normalize,
    verify_pin,
)
from dndc.srd.repository import SRDRepository, load_dataset
from dndc.srd.validate import ValidationIssue, validate_dataset

__all__ = [
    "DEFAULT_NORMALIZED_ROOT",
    "DEFAULT_RAW_ROOT",
    "IngestReport",
    "SRDIngestError",
    "SRDRepository",
    "ValidationIssue",
    "ingest",
    "load_dataset",
    "normalize",
    "validate_dataset",
    "verify_pin",
]
